version: "3.7"
services:
  mongo1:
    image: mongo:latest
    volumes:
      - db-data:/data/db
    restart: always
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: red
      MONGO_INITDB_ROOT_PASSWORD: abc123red
    networks:
      - red_development
  mongo2:
    image: mongo:4.1.11
    volumes:
      - db-data:/data/db
    restart: always
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: red
      MONGO_INITDB_ROOT_PASSWORD: abc123red
    networks:
      - red_development
  elastic:
    image: elasticsearch:6.6.1
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - Elogger.level=TRACE
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/data/elasticsearch
    ports:
      - 9200:9200
    networks:
      - red_development
  elastic_template:
    depends_on:
      - elastic
    build:
      context: ./elastic
    networks:
      - red_development
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - red_development
  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
    command: server /data
    volumes:
      - s3:/data
    environment:
      MINIO_ACCESS_KEY: LSNHBN6JEG3ADALWGBGO
      MINIO_SECRET_KEY: PSvKinHscx8OjznqbHCUB2h7GC8f7ZNibrQLXW6x
    networks:
      - red_development
  red-server:
    build:
      context: ""
      args:
        - somevar=1
        - image=node:10.12.1
    restart: on-failure
    volumes:
      - /etc/red:/etc/red
networks:
  red_development:
    driver: bridge
volumes:
  db-data:
    driver: local
  s3:
    driver: local
  esdata:
    driver: local
